name: Build Assets

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:         

      - name: Afficher le répertoire actuel
        run: pwd
        
      - name: Lister les fichiers dans le répertoire courant
        run: ls -la
                    
      - name: Build assets with Yarn
        run: yarn dev

    outputs:
      success: true
